apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
  labels:
    app: order-service-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
  selector:
    app: order-service